version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - noidea-network
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  identity-service:
    build: ./identity-service
    container_name: identity-service
    ports:
      - "12000:12000"
    networks:
      - noidea-network
    depends_on:
      - rabbitmq
    environment:
      SERVER_PORT: 12000

      APPLICATION_SECURITY_JWT_SECRET_KEY: VGhpcy1pcy1teS1zZWN1cmUta2V5LTI1Ni1iaXRzLWxvbmc=
      APPLICATION_SECURITY_JWT_EXPIRATION: 1h
      APPLICATION_ACTION_TOKEN_VERIFICATION_EXPIRATION: 15m

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password


  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "12001:12001"
    networks:
      - noidea-network
    depends_on:
      - rabbitmq
    environment:
      SERVER_PORT: 12001

      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: noidea.app.sender@gmail.com
      SPRING_MAIL_PASSWORD: mlkn cjrd uimg txby

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password

networks:
  noidea-network:
    driver: bridge