spring.application.name=gateway

server.port=${SERVER_PORT:8080}

spring.graphql.graphiql.enabled=true

# Identity Service
services.identity-service-uri=${IDENTITY_SERVICE_URI:http://localhost:12000/graphql}

# Movie Catalog Service
services.movie-catalog-service-uri=${MOVIE_CATALOG_SERVICE_URI:http://localhost:12001/graphql}

# Activity Tracking Services
services.activity-query-service-uri=${ACTIVITY_QUERY_SERVICE_URI:http://localhost:12004/graphql}
services.activity-command-service-uri=${ACTIVITY_COMMAND_SERVICE_URI:http://localhost:12003/graphql}


