name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build identity-service with Maven
        run: ./identity-service/mvnw -f ./identity-service/pom.xml clean install

      - name: Build notification-service with Maven
        run: ./notification-service/mvnw -f ./notification-service/pom.xml clean install